config/routes.rb
Rails.application.routes.draw do

  get 'pages/index'

  get "pages/getinstagramposts" => "pages#getinstagramposts", :as => "getinstagramposts"
  
  resources :pages

  root 'pages#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
	validates_uniqueness_of :hashtags
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_page, only: [:show, :edit, :update, :destroy]

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all.order("id desc").page(params[:page]).per_page(8)
    
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
  end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def getinstagramposts
    @medias = Array.new
    $checkerarray = Array.new
    fulltext = Instagram.tag_recent_media('Poems', options = {:count => 10})
    
    fulltext.each do |posts|
      #puts posts
      if posts['tags'].length > 5 && posts['tags']
        #saverthing = posts['tags']
        #puts posts['tags'].to_s
        @medias << posts['tags'].to_s
      
      
        #puts tag

        puts "   ****************************************************

       "
      
       

        
          @medias.each do |m|
            if !$checkerarray.include?(m)
              $checkerarray.push(m)
              @page = Page.new
              @page.hashtags = m.to_s.gsub(/\[/ , '').gsub(/\]/ , '').gsub(/\"/ , '')
              @page.save
             

            end
          end

        
      end

    end
    puts @medias
    
#puts $checkerarray
#redirect_to pages_index_url, notice: 'More hashtags were successfully loaded.'
    #respond_to do |format|
      #format.html { redirect_to pages_url, notice: 'More hashtags were loaded' }
      #format.json { head :no_content }
    #end
#render :nothing => true
redirect_to pages_path, notice: 'More hashtags were successfully loaded.'
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:hashtags)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mainpage_helper.rb
module MainpageHelper
end

app/helpers/mainpages_helper.rb
module MainpagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>#HashtagPoems</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
 <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.4/themes/smoothness/jquery-ui.css" />
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
		<div class="left">
<%= yield %>
</div>
</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hashtags %><br>
    <%= f.text_field :hashtags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>#HashtagPoems</h1>

<div >
<%= link_to "Load Poems", '/pages/getinstagramposts',:class => "btn"%>
<%= @medias %>
</div>
<div>
<table class = "container">
  <thead>
    <tr>
      <th>Hashtags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
       
      <tr>
        <td><%= page.hashtags %></td>
        <td><%#= link_to 'Show', page %></td>
        <td><%#= link_to 'Edit', edit_page_path(page) %></td>
        <td><%#= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>

      </tr>
      <tr><td> ---------------------------------------------------------------------------------------------</td></tr>

    <% end %>

  </tbody>

</table>
</div>
<div><%= will_paginate @pages, previous_label: h("<- Previous"), next_label: h("Next ->") %></div>
<br>

<%#= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Hashtags:</strong>
  <%= @page.hashtags %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>